### PR TITLE
Temporarily removed dpi scaling

### LINKED ISSUE #3: Version selector wider range
The version selector shows all available versions to download.
Not everything of the select can be read.
image

### PR DESCRIPTION
**Pull request by vScherb**
For the settings the setting was moved after the init.
In the SimpleR DPI scaling needed to be activated.

Fixes #3

### CODE REVIEW

**Comment by vScherb** [comment]
The Problem still exists when compiling 'compile with options'.
F5 and build without any options will not overlap the lables.

This problem is maybe caused by the Au3Stripper

**Comment by GerRudi** [comment]
Please comment out _Metro_EnableHighDPIScaling()  in both files for now

**Comment by vScherb** [comment]
Removed the calls completely as they can always be restored and leads to less code pollution/noise.

**Comment by vScherb** [comment]
Is somethingmissing @GerRudi?
Or can it be merged and closed

**Comment by GerRudi** [comment]
Closed as already merged in dev

**Pull request closed without merging**
